import Head from 'next/head';
import Link from 'next/link';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram } from 'react-icons/ai';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>Bakshi_Codes</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="" target="_blank">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2>Bakshi</h2>
            <h3>Front-End Developer!</h3>
            <p>Whether it&#39;s a business or personal, a portfolio is a must in today&#39;s world!</p>
          </div>
          <div>
            <Link href="#">
              <AiFillTwitterCircle />
            </Link>
            <Link href="#">
              <AiFillInstagram />
            </Link>
            <Link href="#">
              <AiFillLinkedin />
            </Link>
          </div>
          <div></div>
        </section>
      </main>
    </>
  )
}
